package:
  name: tlhcrsfinder
  version: "1.0.0"  # Change this to your desired version

source:
  git_url: https://github.com/samtobam/TLHcrsFinder.git
  git_rev: main
   
build:
  number: 0 # Increment with each new build
  scripts:

requirements:
  build:
  - conda-forge::gxx_linux-64
  - make
  - git

  run:
  - bioconda::bedtools=2.31.1
  - bioconda::mash=2.3
  - bioconda::seqkit=2.10.1y
  - bioconda::minimap2=2.30
  - bioconda::mummer4=4.0.1
  - conda-forge::r-base=4.4.3
  - conda-forge::r-gggenomes=1.0.1
  - conda-forge::r-svglite=2.2.1
  - bioconda::bioconductor-iranges=2.40.0
  - samtools=1.6
  - bioconda::blast=2.17.0
  - bioconda::cd-hit=4.8.1


test:
  commands:
    - "TLHcrsFinder.sh --help"

about:
  home: "https://github.com/samtobam/TLHcrsFinder"
  summary: "Telomere-Linked-Helicase Containing RegionS (TLHcrs) repeat detection and analysis tool"
