package:
  name: tlrfinder
  version: "1.0.1"  # Change this to your desired version

source:
  git_url: https://github.com/samtobam/TLRFinder.git
  git_rev: main
   
build:
  number: 0 # Increment with each new build
  scripts:

requirements:
  build:
  - conda-forge::gxx_linux-64
  - make
  - git

  run:
  - bioconda::bedtools=2.31.1
  - bioconda::mash=2.3
  - bioconda::seqkit=2.10.1
  - bioconda::minimap2=2.28
  - bioconda::mummer4=4.0.1
  - conda-forge::r-base=4.4.0
  - conda-forge::r-gggenomes=1.0.1
  - conda-forge::r-svglite=2.1.3
  - bioconda::bioconductor-iranges=2.40.0
  - samtools=1.6
  - bioconda::blast=2.16.0
  - bioconda::cd-hit=4.8.1
  - bioconda::mashtree=1.4.6
  - bioconda::lz-ani=1.2.3
  - bioconda::bioconductor-ggtree=3.14.0
  - conda-forge::r-phytools=2.4_4
  - conda-forge::r-aplot=0.2.8
  - conda-forge::r-ggplot2=3.5.2

test:
  commands:
    - "TLRFinder.sh --help"

about:
  home: "https://github.com/samtobam/TLRFinder"
  summary: "Telomere-Linked-Repeat (TLR) detection and analysis tool"
